### ISSUE TITLE
Submit to packagist?

### ISSUE THREAD

**Issue by Lewiscowles1986** [edent/QR-Generator-PHP#1]
Hello,

Thanks for writing this.

I'd very much like to use this project within a plugin for https://github.com/idno/known mapkyca/known2fa/issues/8 but using modern PHP dependency management and autoloading through composer.

One of the blockers is this being available via packagist.

I know I could put under my own namespace on packagist, but I'd have only added a composer.json and lockfile to what seems to be a self-contained library. This could create confusion and make the chain of up-streaming any changes needlessly long.

Would you be open to a PR, or see yourself registering this with packagist, so it can be used within composer and modern PHP?

## Benefits

- ability to use within composer
- ability to credit you for your work
- ability to provide context (oh, X isn't working, but I see a new release)

**Comment by edent** [comment]
I haven't updated this code since 2013. I have no intention of doing anything more with it. I've never used Packagist. 

Please fork it and do what you please. I think it is under BSD.
