### ISSUE TITLE
Problem with white background in PNG output of QR code

### ISSUE THREAD

**Issue by sametocak** [edent/QR-Generator-PHP#2]
When you run the QR code output in PNG format, the background appears white and there is a border. What is the transparent and no background option?

**Comment by edent** [comment]
Hi @sametocak - this repository hasn't been updated in 13 years.  At the moment, it doesn't support transparency.

If you become a sponsor, I will add the feature for you.

**Comment by sametocak** [comment]
of course. I'll leave you some coffee money here, thank you very much, you are very kind.

https://www.patreon.com/edent

**Comment by sametocak** [comment]
> Hi @sametocak - this repository hasn't been updated in 13 years. At the moment, it doesn't support transparency.
> 
> If you become a sponsor, I will add the feature for you.

If this will take up too much of your time, I can only ask you to remove the borders of the QR code, for example as follows.


<img width="401" alt="Ekran Resmi 2024-01-11 15 09 21" src="https://github.com/edent/QR-Generator-PHP/assets/10333239/90a9e89e-f712-486d-bfce-37fb7b5ebb35">I don't want it like this

<img width="275" alt="Ekran Resmi 2024-01-11 15 09 42" src="https://github.com/edent/QR-Generator-PHP/assets/10333239/52171488-8236-44fb-9730-be6a50595a35"> I want it that way
